name: CI

on:
  pull_request:

jobs:
  commit-lint:
    name: Commit Lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@baa1b236f990293a1b2d94c19e41c2313a85e749 # v6.0.2

  code-quality:
    name: Code Quality
    needs: commit-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Biome CLI
        uses: biomejs/setup-biome@1cbe33ead22c7a2fded3b52fa2893611c815c9b5 # v2.2.1
      - name: Run Biome
        run: biome ci

  build-and-test:
    needs: code-quality
    strategy:
      fail-fast: false
      matrix:
        node:
          - 22
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: "${{matrix.platform}} w/ Node.js ${{matrix.node}}.x"
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true
      - name: "Use Node.js ${{matrix.node}}.x"
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: ${{matrix.node}}.x
      - name: Set up Docker
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
      - run: npm install
      - run: node ./tools/build-wasm.js
      - run: npm run typecheck
      - run: npm run build
      - run: npm test
